### ISSUE TITLE
单词本隔三岔五就需要重新登录，不知其他人是否有这个问题

### ISSUE THREAD

**Issue by Bob-Yuan** [g8up/youDaoDict#28]

**Comment by g8up** [comment]
cookie 是有道单词登录页控制的，为了保护用户隐私，扩展保持操守，不动用户 cookie。
我看了下登录一次，大概有效期在一个月左右。这个时效只能顺从网页逻辑了。

**Comment by Bob-Yuan** [comment]
感谢回复！
可能是因为我在不同设备登录同一个账号，导致cookie失效了




------------------ 原始邮件 ------------------
发件人: "g8up"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 晚上10:29
收件人: "g8up/youDaoDict"<youDaoDict@noreply.github.com>;
抄送: "袁博"<yuanbo95@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [g8up/youDaoDict] 单词本隔三岔五就需要重新登录，不知其他人是否有这个问题 (#28)




cookie 是有道单词登录页控制的，为了保护用户隐私，扩展保持操守，不动用户 cookie。
 我看了下登录一次，大概有效期在一个月左右。这个时效只能顺从网页逻辑了。
