### ISSUE TITLE
chrome 45 会自动停止额外flash播放，导致无法自动播放音频

### ISSUE THREAD

**Issue by XGHeaven** [g8up/youDaoDict#3]
就是我在划词的时候就会出现这样的情况：
![image](https://cloud.githubusercontent.com/assets/9291212/10074889/282cab38-6305-11e5-8a82-e3d187c0e41c.png)
点击一下那个东西之后，才可以发出声音
以前的是没有这种情况的，建议直接从flash切换到h5的音频播放

**Comment by g8up** [comment]
@XGHeaven 谢谢热心反馈，我近期解决~

**Comment by g8up** [comment]
@XGHeaven 确认一下，你是否勾选了配置页里的`自动朗读`那一项设置？

**Comment by XGHeaven** [comment]
@g8up 确实是开启了

**Comment by g8up** [comment]
@XGHeaven 今日凌晨发布了 v3.1.4 ,修改为“HTML5 的音频播放”，留意一下啊~

**Comment by XGHeaven** [comment]
@g8up 好的呢
