### ISSUE TITLE
已经登录，点击加入单词本，仍然提示需要登录，家里公司都这样

### ISSUE THREAD

**Issue by hiblacker** [g8up/youDaoDict#32]
![image](https://user-images.githubusercontent.com/22385375/57993016-bab67880-7ae9-11e9-8531-881ccae3daaa.png)
但其实已经加入了单词本
![image](https://user-images.githubusercontent.com/22385375/57993028-cace5800-7ae9-11e9-83da-d6e64d619676.png)

**Comment by g8up** [comment]
我在不同终端使用时，也遇到过类似登录短暂问题。
在 #28 有关注过。
也许如你推断，多端登录有冲突。有道这个单词页面看似“年久失修”了。

如果我做个单词本，你会用吗？

**Comment by hiblacker** [comment]
@g8up  感谢回复。 现在使用的是3.2.8版
我可能没描述清楚， 不是登录短暂的问题。
我扫码登录后，依然弹窗提示我 ‘需要登录，是否打开登录页？’  点击确定，不需要登录直接跳到单词列表页面了。
之前是虽然提示需要登录，但其实已经成功加入单词本，现在不会加入单词本了

```
如果我做个单词本，你会用吗？
```
会用。
我是一名前端开发者，如果您需要，希望能加入到页面的开发中来~

**Comment by hiblacker** [comment]
问题已修复，感谢作者
